---
kind: Namespace
apiVersion: v1
metadata:
  name: rstudio

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio
  namespace: rstudio
  labels:
    app: rstudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rstudio
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
      - name: rstudio
        image: rocker/rstudio:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8787
        env:
        - name: PASSWORD
          value: "rstudio"

        resources:
          requests:
            memory: "2Gi"
            cpu: "100m"
            #ephemeralStorage: "100Mi"
          limits:
            memory: "4Gi"
            #ephemeralStorage: "200Mi"

        livenessProbe:
          httpGet:
            path: /health-check
            port: 8787
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 10
        startupProbe:
          httpGet:
            path: /health-check
            port: 8787
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          # -- failureThreshold * periodSeconds should be strictly > worst case startup time
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8787
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: rstudio-service
  namespace: rstudio
  labels:
    app: rstudio
spec:
  ports:
    - port: 8787
      targetPort: 8787
      name: http
  selector:
    app: rstudio